### ISSUE TITLE
Timeout when uploading Source files to MediaWiki

### ISSUE THREAD

**Issue by gjost** [denshoproject/encyc-psms#17]
When a user creates a new `Source` object in `encyc-psms` the Django app receives the uploaded file and then uploads it to `encyc-mw` MediaWiki.  This is done during the request/response cycle because we figured the files were small enough to not justify setting up Celery for background processing.  After updating code use `mwclient` instead of `requests` these uploads to MediaWiki are now failing.

### /var/log/nginx/psms.log:
```
192.168.1.10 - - [08/Sep/2020:13:04:10 -0700] "POST /admin/sources/source/add/ HTTP/1.1" 500 271031 "http://encycpsms.local/admin/sources/source/add/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36"
```
### /var/log/encyc/psms.log:
```
2020-09-08 13:03:33,925 DEBUG    [models.save]  save(Source object (None))
2020-09-08 13:03:33,928 DEBUG    [base.get_thumbnail]  Getting thumbnail for file [sources/N/None/facepalm-picard_Be1bIGT.jpg] at [260]
2020-09-08 13:03:33,932 DEBUG    [base._create_thumbnail]  Creating thumbnail file [cache/11/fa/11fa0dda1f6578b4740d7528b8709715.jpg] at [260] with [{'format': 'JPEG', 'quality': 95, 'colorspace': 'RGB', 'upscale': True, 'crop': False, 'cropbox': None, 'rounded': None, 'padding': False, 'padding_color': '#ffffff', 'image_info': {'jfif': 257, 'jfif_version': (1, 1), 'dpi': (72, 72), 'jfif_unit': 1, 'jfif_density': (72, 72)}}]
2020-09-08 13:03:33,974 DEBUG    [base.get_thumbnail]  Getting thumbnail for file [sources/N/None/facepalm-picard_Be1bIGT.jpg] at [700]
2020-09-08 13:03:33,977 DEBUG    [base._create_thumbnail]  Creating thumbnail file [cache/b9/a2/b9a2114cda7514a0ca9fab1afe7a7281.jpg] at [700] with [{'format': 'JPEG', 'quality': 95, 'colorspace': 'RGB', 'upscale': True, 'crop': False, 'cropbox': None, 'rounded': None, 'padding': False, 'padding_color': '#ffffff', 'image_info': {'jfif': 257, 'jfif_version': (1, 1), 'dpi': (72, 72), 'jfif_unit': 1, 'jfif_density': (72, 72)}}]
2020-09-08 13:03:34,030 DEBUG    [models.wiki_sync]  wiki_sync(Source object (2535))
2020-09-08 13:03:34,031 DEBUG    [wiki._login]  initializing
2020-09-08 13:03:34,031 DEBUG    [wiki._login]  no http passwd
2020-09-08 13:03:34,033 DEBUG    [connectionpool._new_conn]  Starting new HTTP connection (1): encycmw.local:80
2020-09-08 13:03:34,563 DEBUG    [connectionpool._make_request]  http://encycmw.local:80 "GET /api.php?meta=siteinfo%7Cuserinfo%7Cuserinfo&siprop=general%7Cnamespaces&uiprop=groups%7Crights%7Cblockinfo%7Chasmsg&continue=&action=query&format=json HTTP/1.1" 200 None
2020-09-08 13:03:34,564 DEBUG    [wiki._login]  <Site object 'encycmw.local/'>
2020-09-08 13:03:34,564 DEBUG    [wiki._login]  logging in
2020-09-08 13:03:34,832 DEBUG    [connectionpool._make_request]  http://encycmw.local:80 "GET /api.php?meta=tokens&type=login&action=query&format=json HTTP/1.1" 200 None
2020-09-08 13:03:36,652 DEBUG    [connectionpool._make_request]  http://encycmw.local:80 "POST /api.php HTTP/1.1" 200 None
2020-09-08 13:03:36,654 WARNING  [client.handle_api_result]  Main-account login via action=login is deprecated and may stop working without warning. To continue login with action=login, see [[Special:BotPasswords]]. To safely continue using main-account login, see action=clientlogin.
2020-09-08 13:03:37,634 DEBUG    [connectionpool._make_request]  http://encycmw.local:80 "GET /api.php?meta=userinfo%7Cuserinfo&uiprop=groups%7Crights%7Cblockinfo%7Chasmsg&continue=&action=query&format=json HTTP/1.1" 200 None
2020-09-08 13:03:37,635 DEBUG    [wiki._login]  <Site object 'encycmw.local/'>
2020-09-08 13:03:37,635 DEBUG    [wiki._login]  done
2020-09-08 13:03:37,904 DEBUG    [connectionpool._make_request]  http://encycmw.local:80 "GET /api.php?prop=info%7Cimageinfo&titles=File%3Addr-testing-135-1.jpg&inprop=protection&iiprop=timestamp%7Cuser%7Ccomment%7Curl%7Csize%7Csha1%7Cmetadata%7Carchivename&continue=&meta=userinfo&uiprop=blockinfo%7Chasmsg&action=query&format=json HTTP/1.1" 200 None
2020-09-08 13:03:37,905 DEBUG    [models.wiki_sync]      keys: file:----:----:----
2020-09-08 13:03:37,905 DEBUG    [models.wiki_sync]      functions: ['upload', 'update', 'link']
2020-09-08 13:03:37,905 DEBUG    [models.wiki_sync]  _wiki_upload
2020-09-08 13:03:37,905 DEBUG    [models._wiki_upload]  _wiki_upload(Source object (2535))
2020-09-08 13:03:37,905 DEBUG    [models._wiki_upload]          /var/www/encycpsms/media/sources/N/None/facepalm-picard_Be1bIGT.jpg
2020-09-08 13:03:37,905 DEBUG    [models._wiki_upload]          > /var/www/encycpsms/media/sources/N/None/ddr-testing-135-1.jpg
2020-09-08 13:03:37,906 DEBUG    [wiki.upload_file]  upload_file(/var/www/encycpsms/media/sources/N/None/ddr-testing-135-1.jpg)
2020-09-08 13:03:37,906 DEBUG    [wiki.upload_file]  page_name ddr-testing-135-1.jpg
2020-09-08 13:03:38,592 DEBUG    [connectionpool._make_request]  http://encycmw.local:80 "GET /api.php?prop=info%7Cimageinfo&titles=File%3Addr-testing-135-1.jpg&inprop=protection&iiprop=timestamp%7Cuser%7Ccomment%7Curl%7Csize%7Csha1%7Cmetadata%7Carchivename&continue=&meta=userinfo&uiprop=blockinfo%7Chasmsg&action=query&format=json HTTP/1.1" 200 None
2020-09-08 13:03:38,593 DEBUG    [wiki.upload_file]  wf <Image object 'b'File:Ddr-testing-135-1.jpg'' for <Site object 'encycmw.local/'>>
2020-09-08 13:03:38,593 DEBUG    [wiki.upload_file]  f <_io.BufferedReader name='/var/www/encycpsms/media/sources/N/None/ddr-testing-135-1.jpg'>
2020-09-08 13:03:38,929 DEBUG    [connectionpool._make_request]  http://encycmw.local:80 "GET /api.php?prop=info%7Cimageinfo&titles=File%3Addr-testing-135-1.jpg&inprop=protection&iiprop=timestamp%7Cuser%7Ccomment%7Curl%7Csize%7Csha1%7Cmetadata%7Carchivename&continue=&meta=userinfo&uiprop=blockinfo%7Chasmsg&action=query&format=json HTTP/1.1" 200 None
2020-09-08 13:03:39,857 DEBUG    [connectionpool._make_request]  http://encycmw.local:80 "GET /api.php?meta=tokens&type=csrf&action=query&format=json HTTP/1.1" 200 None
2020-09-08 13:04:10,210 ERROR    [log.log_response]  Internal Server Error: /admin/sources/source/add/
Traceback (most recent call last):
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='encycmw.local', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1580, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1093, in save_model
    obj.save()
  File "/opt/encyc-psms/psms/sources/models.py", line 155, in save
    self.wiki_sync(update_display) # TODO: celery
  File "/opt/encyc-psms/psms/sources/models.py", line 422, in wiki_sync
    response = self.__getattribute__(function_name)(mw)
  File "/opt/encyc-psms/psms/sources/models.py", line 445, in _wiki_upload
    response = mw.upload_file(dest, comment='Uploaded by PSMS/Tansu')
  File "/opt/encyc-psms/psms/sources/wiki.py", line 63, in upload_file
    comment=comment,
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/mwclient/client.py", line 715, in upload
    data = self.raw_call('api', postdata, files)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/mwclient/client.py", line 399, in raw_call
    stream = self.connection.request(http_method, url, **args)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='encycmw.local', port=80): Read timed out. (read timeout=30)
```

### /var/log/nginx/encycmw.log
```
192.168.1.101 - - [08/Sep/2020:13:03:34 -0700] "GET /api.php?meta=siteinfo%7Cuserinfo%7Cuserinfo&siprop=general%7Cnamespaces&uiprop=groups%7Crights%7Cblockinfo%7Chasmsg&continue=&action=query&format=json HTTP/1.1" 200 3535 "-" "mwclient/0.10.1 (https://github.com/mwclient/mwclient)"
192.168.1.101 - - [08/Sep/2020:13:03:34 -0700] "GET /api.php?meta=tokens&type=login&action=query&format=json HTTP/1.1" 200 111 "-" "mwclient/0.10.1 (https://github.com/mwclient/mwclient)"
192.168.1.101 - - [08/Sep/2020:13:03:36 -0700] "POST /api.php HTTP/1.1" 200 446 "-" "mwclient/0.10.1 (https://github.com/mwclient/mwclient)"
192.168.1.101 - - [08/Sep/2020:13:03:37 -0700] "GET /api.php?meta=userinfo%7Cuserinfo&uiprop=groups%7Crights%7Cblockinfo%7Chasmsg&continue=&action=query&format=json HTTP/1.1" 200 1040 "-" "mwclient/0.10.1 (https://github.com/mwclient/mwclient)"
192.168.1.101 - - [08/Sep/2020:13:03:37 -0700] "GET /api.php?prop=info%7Cimageinfo&titles=File%3Addr-testing-135-1.jpg&inprop=protection&iiprop=timestamp%7Cuser%7Ccomment%7Curl%7Csize%7Csha1%7Cmetadata%7Carchivename&continue=&meta=userinfo&uiprop=blockinfo%7Chasmsg&action=query&format=json HTTP/1.1" 200 412 "-" "mwc
lient/0.10.1 (https://github.com/mwclient/mwclient)"
192.168.1.101 - - [08/Sep/2020:13:03:38 -0700] "GET /api.php?prop=info%7Cimageinfo&titles=File%3Addr-testing-135-1.jpg&inprop=protection&iiprop=timestamp%7Cuser%7Ccomment%7Curl%7Csize%7Csha1%7Cmetadata%7Carchivename&continue=&meta=userinfo&uiprop=blockinfo%7Chasmsg&action=query&format=json HTTP/1.1" 200 412 "-" "mwc
lient/0.10.1 (https://github.com/mwclient/mwclient)"
192.168.1.101 - - [08/Sep/2020:13:03:38 -0700] "GET /api.php?prop=info%7Cimageinfo&titles=File%3Addr-testing-135-1.jpg&inprop=protection&iiprop=timestamp%7Cuser%7Ccomment%7Curl%7Csize%7Csha1%7Cmetadata%7Carchivename&continue=&meta=userinfo&uiprop=blockinfo%7Chasmsg&action=query&format=json HTTP/1.1" 200 412 "-" "mwc
lient/0.10.1 (https://github.com/mwclient/mwclient)"
192.168.1.101 - - [08/Sep/2020:13:03:39 -0700] "GET /api.php?meta=tokens&type=csrf&action=query&format=json HTTP/1.1" 200 110 "-" "mwclient/0.10.1 (https://github.com/mwclient/mwclient)"
192.168.1.101 - - [08/Sep/2020:13:04:09 -0700] "POST /api.php HTTP/1.1" 499 0 "-" "mwclient/0.10.1 (https://github.com/mwclient/mwclient)"
```

### /var/log/nginx/encycmw.err
```
2020/09/08 13:04:09 [error] 953#953: *95 FastCGI sent in stderr: "on failed: invalid range in character class at offset 4 in /opt/encyc-mw/htdocs/includes/media/FormatMetadata.php on line 1860PHP message: PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 4 in /opt/encyc-mw/
htdocs/includes/media/FormatMetadata.php on line 1860PHP message: PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 4 in /opt/encyc-mw/htdocs/includes/media/FormatMetadata.php on line 1860
...
```

**Comment by gjost** [comment]
It's hard to know which side of the `encyc-psms`/Mediawiki divide this error occurs on.

**Comment by gjost** [comment]
Duplicate of https://github.com/denshoproject/encyc-mw/issues/3.
