### ISSUE TITLE
Certain images don't get published to MediaWiki

### ISSUE THREAD

**Issue by gjost** [denshoproject/encyc-psms#18]
Certain images don't get published to the editors mediawiki.  No idea of the pattern yet.

- [x] .jpg
- [x] .jpeg
- [x] .png
- [x] .gif
- [x] .tif
- [x] .pdf
- [x] .mp4

**Comment by pkikawa** [comment]
[for the record: checked boxes indicate a successful upload]

**Comment by pkikawa** [comment]
[APIError at _admin_sources_source_add_.zip](https://github.com/denshoproject/encyc-psms/files/5228590/APIError.at._admin_sources_source_add_.zip)
api error for .tif file (.tif file in zip)


Traceback (most recent call last):
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1580, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1093, in save_model
    obj.save()
  File "/opt/encyc-psms/psms/sources/models.py", line 155, in save
    self.wiki_sync(update_display) # TODO: celery
  File "/opt/encyc-psms/psms/sources/models.py", line 415, in wiki_sync
    response = self.__getattribute__(function_name)(mw)
  File "/opt/encyc-psms/psms/sources/models.py", line 437, in _wiki_upload
    response = mw.upload_file(dest, comment='Uploaded by PSMS/Tansu')
  File "/opt/encyc-psms/psms/sources/wiki.py", line 63, in upload_file
    comment=comment,
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/mwclient/client.py", line 679, in upload
    return self.chunk_upload(file, filename, ignore, comment, text)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/mwclient/client.py", line 760, in chunk_upload
    if self.handle_api_result(info, kwargs=params, sleeper=sleeper):
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/mwclient/client.py", line 332, in handle_api_result
    info['error']['info'], info['error']['*'])

Exception Type: APIError at /admin/sources/source/add/
Exception Value: ('illegal-filename', 'The filename is not allowed.', 'See https://mwstage.densho.org/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.')

**Comment by pkikawa** [comment]
[APIError at _admin_sources_source_add_.zip](https://github.com/denshoproject/encyc-psms/files/5228610/APIError.at._admin_sources_source_add_.zip)
apierror for pdf file (pdf file in zip)

Traceback (most recent call last):
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1580, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1093, in save_model
    obj.save()
  File "/opt/encyc-psms/psms/sources/models.py", line 155, in save
    self.wiki_sync(update_display) # TODO: celery
  File "/opt/encyc-psms/psms/sources/models.py", line 415, in wiki_sync
    response = self.__getattribute__(function_name)(mw)
  File "/opt/encyc-psms/psms/sources/models.py", line 437, in _wiki_upload
    response = mw.upload_file(dest, comment='Uploaded by PSMS/Tansu')
  File "/opt/encyc-psms/psms/sources/wiki.py", line 63, in upload_file
    comment=comment,
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/mwclient/client.py", line 679, in upload
    return self.chunk_upload(file, filename, ignore, comment, text)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/mwclient/client.py", line 760, in chunk_upload
    if self.handle_api_result(info, kwargs=params, sleeper=sleeper):
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/mwclient/client.py", line 332, in handle_api_result
    info['error']['info'], info['error']['*'])

Exception Type: APIError at /admin/sources/source/add/
Exception Value: ('illegal-filename', 'The filename is not allowed.', 'See https://mwstage.densho.org/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.')

**Comment by pkikawa** [comment]
[APIError at _admin_sources_source_add_.zip](https://github.com/denshoproject/encyc-psms/files/5228615/APIError.at._admin_sources_source_add_.zip)
api error from mp4 file (mp4 file in zip)


Traceback (most recent call last):
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1653, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1580, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1093, in save_model
    obj.save()
  File "/opt/encyc-psms/psms/sources/models.py", line 155, in save
    self.wiki_sync(update_display) # TODO: celery
  File "/opt/encyc-psms/psms/sources/models.py", line 415, in wiki_sync
    response = self.__getattribute__(function_name)(mw)
  File "/opt/encyc-psms/psms/sources/models.py", line 437, in _wiki_upload
    response = mw.upload_file(dest, comment='Uploaded by PSMS/Tansu')
  File "/opt/encyc-psms/psms/sources/wiki.py", line 63, in upload_file
    comment=comment,
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/mwclient/client.py", line 679, in upload
    return self.chunk_upload(file, filename, ignore, comment, text)
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/mwclient/client.py", line 760, in chunk_upload
    if self.handle_api_result(info, kwargs=params, sleeper=sleeper):
  File "/opt/encyc-psms/venv/psms/lib/python3.7/site-packages/mwclient/client.py", line 332, in handle_api_result
    info['error']['info'], info['error']['*'])

Exception Type: APIError at /admin/sources/source/add/
Exception Value: ('illegal-filename', 'The filename is not allowed.', 'See https://mwstage.densho.org/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.')

**Comment by gjost** [comment]
Those are Mediawiki errors reported back to `encyc-psms`.  Looks like Mediawiki doesn't like .tif, .pdf, and .mp4 files.

**Comment by GeoffFroh** [comment]
https://www.mediawiki.org/wiki/Manual:Configuring_file_uploads

**Comment by gjost** [comment]
Fixed the problem in `encyc-mw` (https://github.com/denshoproject/encyc-mw/issues/4), please test again.

**Comment by pkikawa** [comment]
pdf, tif and mp4 tested and working now.
